Map<String, Map<String, String>> languageLines = {
  'English': {
    'init': 'Hello World',
    'greeting': 'hello',
    'bye': 'bye',
    'title': 'Risai',
    'play': 'Play Now',
    'language': 'にほんご',
    'loading': 'Loading...',
    'loadingScreen1': 'Collecting waste to recycle!',
    'loadingScreen2': 'Please help us reduce waste!',
    'loadingScreen3': 'Recycle when you can!',
    'points': '+points !',
    'gameRules': 'How to play Resai:',
    'gameRules1': '1 - Tap to drop waste into the bin',
    'gameRules2': '2 - Combine similar items into recyclable items',
    'gameRules3': '3 - Avoid overfilling!',
    'gameRules4': '4 - Recycle as much as you can!',
    'gameRules5': '5 - Earn points and have fun!',
    'legend': 'Combine two similar items to recycle them!',
    'rulesButton': 'How to play',
    'pointsbutton': 'Points',
    'aboutButton': 'About',
    'gameOver': 'So close',
    'wellDone': 'Well Done!',
    'score': 'Score ',
    'playAgain': 'Play Again',
    'scoreHigher': 'Score higher to win a card!',
    'youWon': 'You won a card!',
    'keepUp': 'Keep up the good work!',
    'aboutRisai': 'About Risai',
    'aboutRisai2': 'Risai is a simple game about removing waste!',
    'aboutRisai3':
        'We created this game to mimic how common waste is in our lives and to bring attention to how easy it is to accumulate waste!',
    'aboutRisai4': "You will find that even small waste will be hard to remove",
    'aboutRisai5': 'So please Risai(cle) more and keep the Earth clean!',
    'aboutRisai6': 'Thank you and we hope you enjoy the game!',
    'gameOverSorry':
        'Sorry, the web version does not support this feature yet! (Google Wallet)',
  },
  'Japanese': {
    'init': 'こんにちは、世界',
    'greeting': 'こんにちは',
    'bye': 'じゃね',
    'title': 'リサイ',
    'play': 'プレイ !',
    'language': 'English',
    'loading': 'ローディング...',
    'loadingScreen1': 'リサイクルするためのごみを集めています！',
    'loadingScreen2': 'ごみを減らす手伝いをしてください！',
    'loadingScreen3': 'できるときにリサイクルしてください！',
    'points': '+ポイント !',
    'gameRules': 'リサイの遊び方:',
    'gameRules1': '1 - タップしてゴミをゴミ箱に入れます',
    'gameRules2': '2 - 似たようなアイテムを組み合わせてリサイクル可能なアイテムにします',
    'gameRules3': '3 - オーバーフィルを避けます！',
    'gameRules4': '4 - できるだけ多くリサイクルしてください！',
    'gameRules5': '5 - ポイントを獲得して楽しんでください！',
    'legend': '似た物を組み合わせる',
    'rulesButton': '遊び方',
    'pointsbutton': 'ポイント',
    'aboutButton': 'アバウト',
    'gameOver': 'ゲームオーバー',
    'wellDone': 'おめでとうございます !',
    'score': 'スコア ',
    'playAgain': 'もう一度プレイ',
    'scoreHigher': "スコアを上げてカードを獲得しよう ！",
    'youWon': 'カードを獲得しました！',
    'keepUp': 'がんばって!',
    'aboutRisai': 'リサイについて',
    'aboutRisai2': 'リサイはゴミを取り除くゲームです！',
    'aboutRisai3': 'このゲームは生活でのゴミの溜まり方に注目します！',
    'aboutRisai4': '小さなゴミも取り除くのは難しいです。',
    'aboutRisai5': '地球をきれいに保つためにもっとリサイ(クル)しましょう！',
    'aboutRisai6': 'ありがとうございます。ゲームを楽しんでください！',
    'gameOverSorry': '申し訳ありませんが、Webバージョンではこの機能はまだサポートされていません！(Google ウォレット) ',
  },
};
